sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: p5rp5paTc22I8c5blqtzdk9rCDRCnDihyjq4RWyQsWuBfRS5uhvPDi7sqkBiIpCfqB3vBL2zJInaHgcgxTIcAsaB7E51OJba+h4SXxW5MauvuqXXR7G+iOAXi11uTFjvtpUw0MEk2rcMtoZ124x/TkXPfU9Wl84pdsSnzfUh/+b1Vt8/OZ0CWY24g7+SlJUOVSOkHK52H4JI8ImjG++GaYKD5BXaPdmwYVC88Q+0vHQ6N3zMwcDhSqkj0rpNWUjWXfGi7t1YLTht1AkpAv0EhjjG2+RbBdW9PS/TRSQrLE3qQ+f1ehPJu+YHTHuwbkL3vAmW/cWuVPSDPhy4yzyuXL4FqlibgU3s2jQhZ9ajqrKWNYZGB11gDM3jAMRgQO+8w9rPJ3q/IWJAuHgL/nAQL8BxdD+AUGItb80QToJl/kmQ7+reTyeYFKI2vFVLwd48l7ayf2BUDerEIhMAUu7/pxDkkfCPmiESlJ/AjJChYDYO8ApxIV3rUkLhrKZ1cXmRX2sJZyIKTWfEDi2YTlMyhwjnKAR5yvHJMMtIhKV210fy5TZheI/PwBEVd309wQcvr98bKLu7YpH5nOYPJyPIfEXCrb4wOI92MlpsLhbHnxZeZbJ2RdpA8oZVgC5Erka6nZ679C+xDnuDqNKsouqA1jKXX92d5YHy8yL5CcUezo4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Men-of-Invention-and-Industry_725
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy